src/mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage.views import homepage
from django.contrib.admin import AdminSite
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views #new
urlpatterns = [
    path('admin/login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='capply_login'), #new
    path('admin/', admin.site.urls, name = "capply_admin"),
    path('', homepage, name="home"),
    path('', include('homepage.urls')),
    path('', include('category.urls')),
    path('', include('user.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


class CustomAdminSite(AdminSite):
    site_header = 'CAPPLY Administration'
    site_title = 'CAPPLY Admin'

admin.site.__class__ = CustomAdminSite

src/user/urls.py
from django.urls import path
from .views import edit_profile, generate_cv_pdf, change_password, moderator_request_view
urlpatterns = [
     path('profile_edit/', edit_profile, name="profile_edit"),
     path('change-password',change_password, name="change_password"),
     path('cv-form/', generate_cv_pdf, name='form_pdf'),
     path('moderator-request/', moderator_request_view, name='moderator_request'),

]

src/user/models.py
import uuid
from django.conf import settings
from django.db import models
from category.models import Scholarship
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.db import models
from PIL import Image

# PROFILE MODEL
# FAVORITED SCHOLARSHIP MODEL

# PROFILE
class Profile(models.Model):
    user = models.OneToOneField(User, null  =False, on_delete = models.CASCADE)
    profile_pic = models.ImageField(default='images\profile_pics\Default.png', upload_to='images\profile_pics')
    bio = models.TextField(default="This user is lazy and has nothing to say.", max_length=124, null = True, blank = True)
    

    def __str__(self):
        return str(self.user)
    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.profile_pic.path)
        if img.height > 500 or img.width > 500:
            new_img = (500, 500)
            img.thumbnail(new_img)
            img.save(self.profile_pic.path)

def create_profile(sender, instance, created, **kwargs):
    if created:
        ser_profile, _ = Profile.objects.get_or_create(user=instance)
        ser_profile.save()
        
post_save.connect(create_profile, sender=User)


from django.contrib.auth.models import Group, Permission
STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    ]

# MDOERATOR
class ModeratorRequest(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')

    

src/user/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile, ModeratorRequest
from django.contrib.auth.forms import UserCreationForm  

class EditUserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=125, widget= forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=125, widget= forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(max_length=125, widget= forms.TextInput(attrs={'class': 'form-control'}))
    
    class Meta:
        model = User
        fields = ['username', 'last_name', 'first_name']
          
class EditProfileForm(forms.ModelForm):
    profile_pic = forms.ImageField()
    bio = forms.Textarea()
    
    class Meta:
        model = Profile
        fields = ['profile_pic', 'bio']
        widget= {
            'profile_pic' : forms.FileInput(attrs={'class': 'form-control'}),
            'bio' : forms.TextInput(attrs={'class': 'form-control'})
        }
class CreateUserForm(UserCreationForm):
    username = forms.CharField(max_length=125, widget= forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=125, widget= forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Password',max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            self.add_error('password2', 'The passwords do not match.')
        return cleaned_data

from django.contrib.auth.forms import PasswordChangeForm
from django import forms

class CustomPasswordChangeForm(PasswordChangeForm):
    new_field = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    old_password = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].label = "Old Password"

    def clean(self):
        cleaned_data = super(CustomPasswordChangeForm, self).clean()
        return cleaned_data
    
    

    
class CVForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(CVForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            
            
    # Personal Information
    full_name = forms.CharField(label='Full Name', max_length=100)
    email = forms.EmailField(label='Email')
    phone_number = forms.CharField(label='Phone Number', max_length=20, required=False)
    address = forms.CharField(label='Address', max_length=200, required=False)

    # Professional Summary/Objective
    summary = forms.CharField(label='Professional Summary', widget=forms.Textarea)

    # Education
    institution_name = forms.CharField(label='Institution Name', max_length=100)
    degree_earned = forms.CharField(label='Degree Earned', max_length=100)
    field_of_study = forms.CharField(label='Field of Study', max_length=100)
    dates_of_attendance = forms.DateField(label='Dates of Attendance',widget=forms.DateInput(attrs={'type': 'date'}))


    # Experience
    company_name = forms.CharField(label='Company Name', max_length=100)
    job_title = forms.CharField(label='Job Title', max_length=100)
    employment_dates = forms.CharField(label='Employment Dates', max_length=100)
    responsibilities = forms.CharField(label='Responsibilities', widget=forms.Textarea)
    achievements = forms.CharField(label='Achievements', widget=forms.Textarea)

    # Skills
    skills = forms.CharField(label='Skills', widget=forms.Textarea, required=False)

    # Certifications and Training
    certifications = forms.CharField(label='Certifications', widget=forms.Textarea, required=False)

    # Projects
    project_name = forms.CharField(label='Project Name', max_length=100 , required=False)
    purpose = forms.CharField(label='Purpose', widget=forms.Textarea, required=False)
    role = forms.CharField(label='Role', max_length=100)
    technologies_used = forms.CharField(label='Technologies Used', max_length=200, required=False)

    # Awards and Achievements
    awards = forms.CharField(label='Awards', widget=forms.Textarea, required=False)

    # Languages
    languages = forms.CharField(label='Languages', widget=forms.Textarea, required=False)

    # Interests and Hobbies
    interests = forms.CharField(label='Interests and Hobbies', widget=forms.Textarea, required=False)

    # References
    references = forms.CharField(label='References', widget=forms.Textarea, required=False)
    
    image_file = forms.ImageField(label='Image')


        
class ModeratorRequestForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    class Meta:
        model = ModeratorRequest
        fields = ['message']
        
        

src/user/views.py
from django.shortcuts import render
from django.contrib.auth import update_session_auth_hash
from django.shortcuts import render, redirect
from django.contrib.auth.forms import SetPasswordForm
from .forms import EditUserForm, EditProfileForm
from django.http import HttpResponse, HttpResponseRedirect
from .forms import CVForm,ModeratorRequestForm
from django.template.loader import render_to_string
from django.core.files.storage import FileSystemStorage
from xhtml2pdf import pisa
from django.contrib import messages

# EDIT PROFILE
def edit_profile(request):
    if request.method == 'POST':
        form = EditUserForm(request.POST, instance=request.user) 
        profile_form = EditProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            profile_form.save()
            update_session_auth_hash(request, user)
            return redirect('profile')
    else:
        form = EditUserForm(instance=request.user)
        profile_form =EditProfileForm(instance=request.user.profile)
    context = {
        'form': form,
        'profile_form':profile_form
    }
    return render(request, 'user/profile_edit.html', context)

# CHANGE PASSWORD
def change_password(request):
    if request.method == 'POST':
        password_form = SetPasswordForm(user=request.user, data=request.POST)
        
        if password_form.is_valid():
            password_form.save()
            update_session_auth_hash(request, request.user)
            return redirect('profile')
    else:
        password_form = SetPasswordForm(user=request.user)
    
    context = {
        'password_form': password_form,
    }
    return render(request, 'user/change_password.html', context)


from django.template.loader import get_template
import weasyprint
from PIL import Image
import os
from django.conf import settings

# CREATE CV TO PDF
def generate_cv_pdf(request):

    if request.method == 'POST':
        form = CVForm(request.POST, request.FILES)
        if form.is_valid():
                        
            full_name = form.cleaned_data['full_name']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            address = form.cleaned_data['address']
            summary = form.cleaned_data['summary']
            institution_name = form.cleaned_data['institution_name']
            degree_earned = form.cleaned_data['degree_earned']
            field_of_study = form.cleaned_data['field_of_study']
            dates_of_attendance = form.cleaned_data['dates_of_attendance']
            company_name = form.cleaned_data['company_name']
            job_title = form.cleaned_data['job_title']
            employment_dates = form.cleaned_data['employment_dates']
            responsibilities = form.cleaned_data['responsibilities']
            achievements = form.cleaned_data['achievements']
            
            skills = form.cleaned_data['skills']
            certifications = form.cleaned_data['certifications']
            
            project_name = form.cleaned_data['project_name']
            purpose = form.cleaned_data['purpose']
            role = form.cleaned_data['role']
            technologies_used = form.cleaned_data['technologies_used']
            
            awards = form.cleaned_data['awards']
            languages = form.cleaned_data['languages']
            interests = form.cleaned_data['interests']
            references = form.cleaned_data['references']
            image_file = form.cleaned_data['image_file']

            fss = FileSystemStorage()
            file = fss.save(image_file.name, image_file)
            image_url = fss.url(file)

            image_url_with_scheme = f"{request.scheme}://{request.get_host()}{image_url}"
            
            
            # img = Image.open('media/'+image_file.name)
            # left = 100
            # top = 100
            # right = 400
            # bottom = 400
            # cropped_image = img.crop((left, top, right, bottom))
            # cropped_file_path = os.path.join(settings.MEDIA_ROOT, 'cropped_image.jpg')

            # cropped_image.save(cropped_file_path)

            
            context = {
                'full_name': full_name,
                'email': email,
                'phone_number': phone_number,
                'address': address,
                'summary': summary,
                'institution_name': institution_name,
                'degree_earned': degree_earned,
                'field_of_study': field_of_study,
                'dates_of_attendance': dates_of_attendance,
                'company_name': company_name,
                'job_title': job_title,
                'employment_dates': employment_dates,
                'responsibilities': responsibilities,
                'achievements': achievements,
                'skills': skills,
                'certifications': certifications,
                'project_name': project_name,
                'purpose': purpose,
                'role': role,
                'technologies_used': technologies_used,
                'awards': awards,
                'languages': languages,
                'interests': interests,
                'references': references,
                'image_url': image_url_with_scheme
            }
            # img = Image.open(image_url_with_scheme)
            # left = 100
            # top = 100
            # right = 400
            # bottom = 400
            # cropped_image = img.crop((left, top, right, bottom))
            # cropped_image.save(cropped_file_path)


            template = get_template('cv/cv_template.html')
            html = template.render(context)
            
            pdf = weasyprint.HTML(string=html).write_pdf(stylesheets=[weasyprint.CSS(string='@page { margin: 0;page-break-after: always; margin-top:10mm;  }')])

            
            response = HttpResponse(content_type='application/pdf')
            response['Content-Disposition'] = 'attachment; filename="form_submission.pdf"'
            response.write(pdf)
            # html_string = render_to_string('cv/cv_template.html', context)

            # response = HttpResponse(content_type='application/pdf')
            # response['Content-Disposition'] = 'attachment; filename="form_submission.pdf"'

            # pisa.CreatePDF(html_string, dest=response)
            return response
        else:
            form = CVForm()
    else:
        form = CVForm()

    return render(request, 'cv/cv_form.html', {'form': form})

from django.shortcuts import render, redirect
from .forms import CreateUserForm
from django.contrib.auth.models import User

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import CreateUserForm
from django.contrib.auth.models import User, auth




# MODERATOR REQUEST
def moderator_request_view(request):
    if request.method == 'POST':
        form = ModeratorRequestForm(request.POST)
        if form.is_valid():
            moderator_request = form.save(commit=False)
            moderator_request.user = request.user
            moderator_request.save()
            messages.success(request, 'Your request has been submitted successfully.')
            return HttpResponseRedirect(request.META['HTTP_REFERER']) 
    else:
        form = ModeratorRequestForm()
    
    return render(request, 'user/moderator_request.html', {'form': form, 'message':messages})

src/templates/user/change_password.html
{% extends 'profile_base.html' %}
{% block title %} Change Password {% endblock %}
{% block content %}

<section class="section">
  <div class="container mt-5 h-100">
    <div class="row d-flex justify-content-center text-primary align-items-center h-100">
      <div class="col-md-12 col-xl-4">
        <div class="card" style="border-radius: 15px;">
          <div class="card-body text-center">
            <div class="mt-3 mb-4">
              <img src="{{user.profile.profile_pic.url}}" class="rounded-circle img-fluid" style="width: 100px;" />
            </div>
            <h4 class="mb-2">{{ request.user.first_name}} {{ request.user.last_name}}</h4>

            <p class="text-muted mb-4">@{{ request.user.username}} <span class="mx-2"></p>
            <form method="POST" enctype="multipart/form-data" action="{% url 'change_password' %}" class="mx-1 mx-md-4">
              {% csrf_token %}
              <div>
                <label for="id_old_password" class="form-label">Old Password:</label>
                <input type="password" name="old_password" id="id_old_password" class="form-control">
                {% if form.old_password.errors %}
                {% for error in form.old_password.errors %}
                <div class="error">{{ error }}</div>
                {% endfor %}
                {% endif %}
              </div>
              <div>
                <label for="id_new_password1" class="form-label">New Password:</label>
                <input type="password" name="new_password1" id="id_new_password1" class="form-control">
                {% if form.new_password1.errors %}
                {% for error in form.new_password1.errors %}
                <div class="error">{{ error }}</div>
                {% endfor %}
                {% endif %}
              </div>
              <div>
                <label for="id_new_password2" class="form-label">Confirm Password:</label>
                <input type="password" name="new_password2" id="id_new_password2" class="form-control">
                {% if form.new_password2.errors %}
                {% for error in form.new_password2.errors %}
                <div class="error">{{ error }}</div>
                {% endfor %}
                {% endif %}
              </div>
              <div class="d-felx">
                <button type="submit" class="btn btn-primary border-yellow">Save</button>
               
              </div>
            </form>






          </div>
        </div>
      </div>

    </div>
  </div>
  </div>
</section>


{% endblock content %}

src/templates/user/delete_confirmation.html
{% extends 'profile_base.html' %}

{% block content %}

<body>
  <section class="vh-100" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-12 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <a href="{% url 'profile_edit' %}" class="mx-3 mt-3">
              < Back </a>
                <div class="card-body ">
                  <br>

                  <h3 class="text-center">Account delete confirmation</h3><br>
                  {% if message %}
                  <div class="row">
                    <div class="col-12">
                      <div class="alert alert-danger contact__msg" role="alert">
                        {{ message }}
                      </div>
                    </div>
                  </div>
                  {% endif %}
                  <form method="post" action="{% url 'user_delete_confirm' %}" class="mx-1 mx-md-4">
                    {% csrf_token %}
                    <p class="text-muted mb-3">Confirm password:<span class="mx-2"></p>
                    <input type="password" class="form-control" id="confirm_password" name="confirm_password" required>
                    <br><br>

                    <button type="submit" class="btn btn-danger text-primary">Delete Account</button>

                    <a href="{% url 'profile' %}" class="btn btn-primary">Cancel</a>
                  </form>

                  <br><br>

                </div>
          </div>
        </div>

      </div>
    </div>
    </div>
  </section>
</body>

{% endblock content %}

src/templates/user/favorite.html
{% extends 'profile_base.html' %}


{% block content %}

<body>
    <section class="position-relative overflow-hidden ">
        <div class="container mt-lg-5 pt-5">
            <div class=" row align-items-center justify-content-center">
                <div class="card bg-white col-lg-8 m-5 px-5 pb-5 " style="border-radius: 15px;">
                    
                    <a href="{% url 'profile' %}" class="mt-5 ">
                        < Back</a>
                            <h3 class="text-center">Favorited Scholarships</h3>
                            {% for favorite in scholarship_favorite %}
                            <div class="row d-flex align-items-center shadow  justify-content-center card-body">
                                <h5 class="card-title"><a
                                        href="scholarship/{{favorite.scholarship_link}}">{{favorite.scholarship_school}}</a>
                                </h5>
                                <a href="favorite-delete/{{favorite.scholarship_link}}"
                                    class=" p-2  text-danger">Remove</a>
                            </div>
                            {% endfor %}
                            {% if not scholarship_favorite %}
                            <p class="text-center text-primary">No Scholarship added</p>
                            {% endif %}

                </div>
            </div>
        </div>

    </section>
    {% endblock content %}

src/templates/user/login.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Log In - CAPPLY</title>
  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"> -->

  {% include 'snippets/snippet_css_all.html' %}
</head>

<body>

  <section class="vh-100" style="background-color: #1B3764;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Log In</p>
                  <!-- form message -->
                  {% if message  %}
                  <div class="row">
                    <div class="col-12">
                      <div class="alert alert-danger contact__msg"  role="alert">
                        {{ message }}
                      </div>
                    </div>
                  </div>
                  {% endif %}
                  <!-- end message -->
                  {% if request.user.is_authenticated %}
                  <p class="text-sucess">You are logged in!</p>
                  <p class="text-sucess">Welcome {{ request.user.first_name}}!</p>
                  {% else %}
                  <p class="text-danger">You are not logged in, log in to bookmark scholarships!</p>
                  {% endif %}
                  <form method="POST" action="{% url 'login' %}" class="mx-1 mx-md-4">
                    {% csrf_token %}
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input name="username" type="text" id="" class="form-control" required />
                        <label class="form-label" for="form3Example1c">Username</label>
                      </div>
                    </div>

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input name="password" type="password" id="" class="form-control" required />
                        <label class="form-label" for="form3Example4c">Password</label>
                      </div>
                    </div>

                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <button type="submit" class="btn btn-primary btn-lg ">Login</button>
                      <a href="{% url 'home' %}" class="btn btn-primary btn-lg">Back</a>
                    </div>


                  </form>

                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                    class="img-fluid" alt="Sample image">

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>

</html>

src/templates/user/moderator_request.html
{% if messages.success == message  %}
    <ul class="messages">
        {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<form method="post" action="{% url 'moderator_request' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit Request</button>
  </form>
  

src/templates/user/profile_edit.html
{% extends 'profile_base.html' %}
{% block title %} Edit Profile {% endblock %}
{% block content %}

<section class="section">
  <div class="container mt-5 h-100">
    <div class="row d-flex justify-content-center text-primary align-items-center h-100">
      <div class="col-md-12 col-xl-4">
        <div class="card" style="border-radius: 15px;">
          <div class="card-body text-center">
            <div class="mt-3 mb-4">
              <img src="{{user.profile.profile_pic.url}}" class="rounded-circle img-fluid" style="width: 100px;" />
            </div>
            <h4 class="mb-2">{{ request.user.first_name}} {{ request.user.last_name}}</h4>
            {% if form.errors or profile_form.errors %}
            <div class="alert alert-danger alert-dismissible" role="alert">
              <div id="form_errors">
                {% for key, value in form.errors.items %}
                <strong>{{ value }}</strong>
                {% endfor %}
              </div>
              <div id="profile_form_errors">
                {% for key, value in profile_form.errors.items %}
                <strong>{{ value }}</strong>
                {% endfor %}
              </div>
              
            </div>
            {% endif %}
            <p class="text-muted mb-4">@{{ request.user.username}} <span class="mx-2"></p>



            <!-- EDIT PROFILE FORM -->
            <form method="POST" action="{% url 'profile_edit' %}" enctype="multipart/form-data" class="mx-1 mx-md-4">
              {% csrf_token %}
              <div>

                <div class="custom-file">
                  <label for="{{ form.profile_pic.id_for_label }}">Profile Picture</label>
                  <input type="file" name="profile_pic" class="form-control" accept="image/*" id="id_profile_pic">
                </div>
              </div>
              <div>
                <label for="{{ profile_form.bio.id_for_label }}" class="form-label">Bio:</label>
                <input type="text" name="bio" id="id_bio" class="form-control" value="{{ profile_form.bio.value }}">
                {% if profile_form.bio.errors %}
                {% for error in profile_form.bio.errors %}
                <div class="error text-danger">{{ error }}</div>
                {% endfor %}
                {% endif %}
              </div>
              <div>
                <label for="{{ form.username.id_for_label }}" class="form-label">Username:</label>
                <input type="text" name="username" id="id_username" class="form-control"
                  value="{{ form.username.value }}">
                {% if form.username.errors %}
                {% for error in form.username.errors %}
                <div class="error text-danger">{{ error }}</div>
                {% endfor %}
                {% endif %}
              </div>
              <div>
                <label for="{{ form.last_name.id_for_label }}" class="form-label">Last Name:</label>
                <input type="text" name="last_name" id="id_last_name" class="form-control"
                  value="{{ form.last_name.value }}">
                {% if form.last_name.errors %}
                {% for error in form.last_name.errors %}
                <div class="error text-danger">{{ error }}</div>
                {% endfor %}
                {% endif %}
              </div>
              <div class="d-flex flex-row align-items-center mb-4">
                <div class="form-outline flex-fill mb-0">
                  <label for="{{ form.first_name.id_for_label }}" class="form-label">First Name:</label>
                  <input type="text" name="first_name" id="id_first_name" class="form-control"
                    value="{{ form.first_name.value }}">
                  {% if form.first_name.errors %}
                  {% for error in form.first_name.errors %}
                  <div class="error text-danger">{{ error }}</div>
                  {% endfor %}
                  {% endif %}
                </div>
              </div>
              <a href="{% url 'change_password' %}" class='underline bold text-secondary'>Change Password</a><br>

              <button type="submit" class="btn btn-primary border-yellow">Save</button>
              <a href="{% url 'profile' %}" class="btn btn-secondary border-yellow">Cancel</a>
            </form>




          </div>
        </div>
      </div>

    </div>
  </div>
  </div>
</section>


{% endblock content %}